# Generated by Django 5.2.7 on 2025-10-09 16:24

from django.db import migrations


def check_new_building(apps, schema_editor):
    flat = apps.get_model("property", "Flat")
    new_buildings = flat.objects.filter(construction_year__gt=2014)
    old_buildings = flat.objects.filter(construction_year__lt=2015)

    new_buildings.update(new_building=True)
    old_buildings.update(new_building=False)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(check_new_building)
    ]
