# Generated by Django 5.2.7 on 2025-10-16 16:21
from django.db import migrations
from phonenumbers import parse, is_valid_number


def correct_phonenumbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all().iterator():
        correct_number = parse(flat.owners_phonenumber, "RU")
        flat.owner_pure_phone = correct_number
        if(not is_valid_number(flat.owner_pure_phone)):
            flat.owner_pure_phone.national_number = 0000000000
            flat.save()
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(correct_phonenumbers)
    ]
