# Generated by Django 5.2.7 on 2025-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_owners_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, null=True, verbose_name='Являеться ли новостройкой'),
        ),
    ]
