# Generated by Django 5.2.7 on 2025-10-23 16:24

from django.db import migrations


def get_flat_owners(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    for flat in Flat.objects.all().iterator():
        owner, is_created = Owner.objects.get_or_create(
            owner=flat.owner,
            owner_pure_phone=flat.owner_pure_phone
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(get_flat_owners)
    ]

