# Generated by Django 5.2.7 on 2025-11-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_complaint_user_remove_owner_owned_flats_and_more'),
        ('property', '0017_auto_20251102_1432'),
    ]

    operations = [
    ]
