# Generated by Django 5.2.8 on 2025-11-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_merge_20251102_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
